project_id = "bzbuppwzljadulwntjys"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.court-lights]
    verify_jwt = false
  [functions.create-club]
    verify_jwt = false
  [functions.email-notifications]
    verify_jwt = false
  [functions.maintenance]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-captcha]
    verify_jwt = false
