-- Step-by-Step Beta: prepare a tournament for the structured engine from CURRENT active entries.
-- Writes the confirmed spec + draw entries (pairs kept intact). Fixtures are then generated by the
-- existing structured engine (structured_commit). Refuses to touch played/started games.
CREATE OR REPLACE FUNCTION public.step_prepare_draw(p_champ_id uuid, p_spec jsonb, p_entries jsonb, p_rebuild boolean DEFAULT false)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  e jsonb; n_games int; n_played int; n_entries int := 0;
  v_member uuid; v_partner uuid; v_group int; seen uuid[] := '{}';
BEGIN
  IF NOT public.can_manage_tournament(auth.uid(), p_champ_id) THEN
    RAISE EXCEPTION 'Not allowed to manage this tournament' USING ERRCODE = '42501';
  END IF;
  PERFORM 1 FROM public.tournaments WHERE id = p_champ_id FOR UPDATE;
  IF jsonb_typeof(p_spec) <> 'object' OR p_spec->>'architecture' IS DISTINCT FROM 'structured' THEN
    RAISE EXCEPTION 'Refused: not a structured specification';
  END IF;

  SELECT count(*), count(*) FILTER (WHERE winner_member_id IS NOT NULL
           OR COALESCE(lower(status),'') IN ('completed','confirmed','in_progress','live','walkover','forfeit'))
    INTO n_games, n_played FROM public.club_champs_matches WHERE champ_id = p_champ_id;
  IF n_games > 0 AND NOT p_rebuild THEN
    RAISE EXCEPTION 'draw_exists: this tournament already has % game(s). Use Rebuild draw.', n_games;
  END IF;
  IF n_played > 0 THEN
    RAISE EXCEPTION 'results_exist: % game(s) are played or started. The draw cannot be rebuilt; use "Rebuild unplayed games" instead.', n_played;
  END IF;

  -- Validate every draw entry against the current active registrations (single source of truth).
  FOR e IN SELECT * FROM jsonb_array_elements(COALESCE(p_entries,'[]'::jsonb)) LOOP
    v_member := (e->>'member')::uuid; v_partner := NULLIF(e->>'partner','')::uuid; v_group := (e->>'group')::int;
    IF v_member = ANY(seen) OR (v_partner IS NOT NULL AND v_partner = ANY(seen)) THEN
      RAISE EXCEPTION 'pair_integrity: a player appears in the draw more than once';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.club_champs_registrations r
       WHERE r.champ_id = p_champ_id AND r.club_member_id = v_member
         AND COALESCE(r.status,'') NOT IN ('cancelled','withdrawn','declined')
         AND r.partner_member_id IS NOT DISTINCT FROM v_partner
         AND (r.division_choices IS NULL OR cardinality(r.division_choices) = 0 OR v_group = ANY(r.division_choices))) THEN
      RAISE EXCEPTION 'stale_entry: an entry is not a current active registration in that division';
    END IF;
    IF v_partner IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.club_champs_registrations r
       WHERE r.champ_id = p_champ_id AND r.club_member_id = v_partner
         AND COALESCE(r.status,'') NOT IN ('cancelled','withdrawn','declined')
         AND r.partner_member_id = v_member) THEN
      RAISE EXCEPTION 'pair_integrity: a partner''s entry does not point back to the same pair';
    END IF;
    seen := seen || v_member || COALESCE(v_partner, v_member);
  END LOOP;

  -- Clear unplayed structure (none of it has results — checked above).
  DELETE FROM public.club_champs_matches WHERE champ_id = p_champ_id;
  DELETE FROM public.club_champs_rounds WHERE champ_id = p_champ_id;
  DELETE FROM public.tournament_divisions WHERE tournament_id = p_champ_id;

  DELETE FROM public.club_champs_entries WHERE champ_id = p_champ_id;
  INSERT INTO public.club_champs_entries (champ_id, club_member_id, partner_member_id, group_number, order_index)
  SELECT p_champ_id, (x->>'member')::uuid, NULLIF(x->>'partner','')::uuid, (x->>'group')::int, COALESCE((x->>'order')::int, 0)
    FROM jsonb_array_elements(COALESCE(p_entries,'[]'::jsonb)) x;
  GET DIAGNOSTICS n_entries = ROW_COUNT;

  UPDATE public.tournaments SET builder_architecture = 'structured', builder_spec = p_spec WHERE id = p_champ_id;
  RETURN jsonb_build_object('entries', n_entries, 'removed_games', n_games);
END $$;
REVOKE ALL ON FUNCTION public.step_prepare_draw(uuid, jsonb, jsonb, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.step_prepare_draw(uuid, jsonb, jsonb, boolean) TO authenticated, service_role;