/**
 * Structured (Beta) tournament persistence + generation.
 * Order is fixed: spec → validate → persist divisions/stages/pools → rounds → fixtures
 * against those ids → identity validation → insert. Legacy tournaments never come here.
 * The DB trigger `guard_structured_match_identity` enforces the same identity rules.
 */
import { IntegrityError, rankPoolTally, assertNoReentry, contractIssues, isDecided, progressionOf, type FixtureRow, type PlannedStage, type PoolStanding, type StageKind } from "./contract";
import { assertFixtureIdentity, poolDefaultLabel, type HTournament } from "./hierarchy";
import { confirmPlayoffs, generateFromSpec, mappedFixtures, nextStageFixtures, previewPlayoffs, previewTransition, type EngineFixture, type PlayoffPreview, type SpecDivision, type TournamentSpec } from "./engine-service";
import { effectiveTransition, transitionIssues } from "./transition";
import type { TournamentDefinition } from "../smart-builder/definition";
import { engineVerdicts, translateForEngine } from "../smart-builder/engine-support";
import { venuesOutsideSet } from "../smart-builder/venues";
import { rawSchedule, resolveSpecDates, specDateIssues } from "./date-window";

/* ───── spec from the Beta definition ───── */

export function specFromDefinition(input: TournamentDefinition): TournamentSpec {
  // Exactly-representable designs are rewritten to supported stages first (same games, never silenced).
  const { def, translatedDivisions } = translateForEngine(input);
  const tw = { start: def.scheduleDefaults?.startDate ?? null, end: def.scheduleDefaults?.endDate ?? null };
  const stray = venuesOutsideSet(def);
  if (stray.length) throw new IntegrityError("venue_outside", `${stray[0].where}: ${stray[0].venue} is not one of the tournament's venues.`);
  const spec: TournamentSpec = {
    version: 1, architecture: "structured", name: def.name,
    scope: (def as any).event ?? null,
    divisions: def.divisions.map((d) => {
      const stages: PlannedStage[] = [];
      d.sections.forEach((sec) => sec.stages.forEach((st) => {
        let kind: StageKind;
        if (st.kind === "round_robin") kind = st.groups > 1 ? "pools" : "round_robin";
        else if (st.kind === "knockout" || st.kind === "swiss" || st.kind === "placement") kind = st.kind as StageKind;
        else if (st.kind === "cross_pool_league") throw new IntegrityError("unsupported_stage", engineVerdicts(input).find((v) => v.stageId === st.id)?.detail ?? `${d.name} · ${st.name}: a pool-v-pool league can't be generated by the tournament engine.`);
        else throw new IntegrityError("unsupported_stage", `${d.name} · ${st.name}: this stage type can't be generated by the structured engine yet.`);
        const prev = stages[stages.length - 1];
        const s = st.schedule ?? { mode: "unset" };
        stages.push({
          id: st.id, order: stages.length, kind, name: st.name,
          pools: kind === "pools" ? st.groups : undefined,
          poolSize: st.groupSize ?? undefined,
          swissRounds: st.swissRounds ?? undefined,
          tieBreaks: (st as any).tieBreaks ?? undefined,
          legs: (st as any).legs === 2 ? 2 : undefined,
          thirdPlace: (st as any).thirdPlace || undefined,
          discipline: st.discipline ?? undefined,
          progression: prev && (st as any).progression ? { ...(st as any).progression } : undefined,
          drawSize: kind === "knockout" ? st.groupSize ?? undefined : undefined,
          schedule: {
            rule: s.mode === "fixed" ? "fixed" : s.mode === "play_by" ? "play_by" : (s.mode as string) === "window" ? "window" : null,
            // Stage start/end are ONLY the explicit stage-window override; NULL = inherit the tournament window.
            date: (s as any).roundDates?.[0] ?? null,
            deadline: s.mode === "play_by" ? (s as any).endDate ?? null : null,
            start: (s as any).startDate ?? null, end: (s as any).endDate ?? null,
            roundDates: (s as any).roundDates?.length ? [...(s as any).roundDates] : undefined,
          },
          qualify: prev ? {
            perPool: (def.divisions.flatMap((x) => x.sections.flatMap((y) => y.stages)).find((x) => x.id === prev.id)?.advance?.perGroup) ?? 0,
            mapping: st.qualifierMapping ?? null,
            transition: st.qualifierTransition
              ? { ...st.qualifierTransition, positions: [...st.qualifierTransition.positions], sourceStageId: prev.id, destinationStageId: st.id } as any
              : null,
          } : null,
          generation: st.generation ?? (prev ? "owner_approval" : undefined),
        });
      }));
      return {
        divisionId: d.id, label: d.name, unit: d.entry === "pairs" ? "pairs" : "players",
        expectedEntrants: d.sections[0]?.stages[0]?.input?.entrants ?? null,
        seeding: { source: (def as any).event?.seedingSource ?? "entry_order", method: translatedDivisions.has(d.id) ? "banded" : "snake" },
        placements: "champion", stages, entrants: [], poolLabels: d.poolLabels,
        finalStandings: (def as any).finalStandings ?? "last_stage",
      } satisfies SpecDivision;
    }),
  };
  const dateErr = specDateIssues(spec, tw)[0];
  if (dateErr) throw new IntegrityError(dateErr.code, dateErr.message);
  return spec;
}

/* ───── db access (injected so tests can use an in-memory fake) ───── */

export interface Db {
  insert(table: string, rows: Record<string, unknown>[]): Promise<Array<Record<string, any>>>;
  select(table: string, filter: Record<string, unknown>): Promise<Array<Record<string, any>>>;
  update(table: string, filter: Record<string, unknown>, patch: Record<string, unknown>): Promise<void>;
  /** Remove rows by id. Only unplayed games and entries may be removed. */
  remove?(table: string, ids: string[]): Promise<void>;
}

/* ───── all-or-nothing: buffer every write, then commit in ONE server transaction ───── */

export type CommitOp =
  | { op: "insert"; table: string; rows: Record<string, unknown>[] }
  | { op: "delete_unplayed_matches"; ids: string[] }
  | { op: "delete_entries"; ids: string[] };

const uuid = () => (globalThis.crypto?.randomUUID?.() ?? "xxxxxxxx-xxxx-4xxx-8xxx-xxxxxxxxxxxx".replace(/x/g, () => ((Math.random() * 16) | 0).toString(16)));

/**
 * Reads go to the real database (plus pending writes); writes are only collected.
 * `commit` sends everything to the server in one transaction — if any row fails, nothing is saved.
 */
export function bufferedDb(base: Db) {
  const ops: CommitOp[] = [];
  const pending: Record<string, Array<Record<string, any>>> = {};
  const removed = new Set<string>();
  const match = (r: Record<string, any>, f: Record<string, unknown>) => Object.entries(f).every(([k, v]) => r[k] === v);
  const db: Db = {
    async insert(table, rows) {
      const out = rows.map((r) => ({ id: uuid(), ...r }));
      ops.push({ op: "insert", table, rows: out });
      (pending[table] ??= []).push(...out);
      return out;
    },
    async select(table, filter) {
      const real = (await base.select(table, filter)).filter((r) => !removed.has(r.id));
      return [...real, ...(pending[table] ?? []).filter((r) => match(r, filter))];
    },
    async update() { throw new IntegrityError("unsupported", "Updates are not part of structured commits."); },
    async remove(table, ids) {
      if (!ids.length) return;
      if (table === "club_champs_matches") ops.push({ op: "delete_unplayed_matches", ids });
      else if (table === "club_champs_entries") ops.push({ op: "delete_entries", ids });
      else throw new IntegrityError("unsupported", `Cannot remove from ${table}.`);
      ids.forEach((id) => removed.add(id));
    },
  };
  return { db, ops, commit: (tid: string, send: (tid: string, ops: CommitOp[]) => Promise<unknown>) => (ops.length ? send(tid, ops) : Promise.resolve(null)) };
}

/** Run an engine action against a buffer and commit it atomically. */
export async function atomically<T>(base: Db, tid: string, send: (tid: string, ops: CommitOp[]) => Promise<unknown>, fn: (db: Db) => Promise<T>): Promise<T> {
  const b = bufferedDb(base);
  const result = await fn(b.db); // any IntegrityError here means nothing was sent
  await b.commit(tid, send);
  return result;
}

export interface StructureIds {
  division: Record<string, string>;
  stage: Record<string, string>; // `${divKey}/${stageKey}`
  pool: Record<string, string>; // `${divKey}/${stageKey}/${index}`
  stageKind: Record<string, StageKind>;
}

/** Persist divisions → stages → pools. Idempotent: re-uses existing rows by spec_key. */
export async function persistStructure(db: Db, tid: string, spec: TournamentSpec): Promise<StructureIds> {
  const ids: StructureIds = { division: {}, stage: {}, pool: {}, stageKind: {} };
  const [tour] = await db.select("tournaments", { id: tid });
  if (tour?.builder_architecture !== "structured") throw new IntegrityError("not_structured", "Only structured (Beta) tournaments use this path.");
  for (const [di, d] of spec.divisions.entries()) {
    let [div] = await db.select("tournament_divisions", { tournament_id: tid, spec_key: d.divisionId });
    div ??= (await db.insert("tournament_divisions", [{ tournament_id: tid, spec_key: d.divisionId, label: d.label, unit: d.unit, sort_order: di }]))[0];
    ids.division[d.divisionId] = div.id;
    for (const st of d.stages) {
      let [row] = await db.select("tournament_stages", { division_id: div.id, spec_key: st.id });
      const prev = d.stages.find((s) => s.order === st.order - 1);
      // Explicit, persisted progression rule: stable stage ids + pool indexes, never display names.
      const tr = prev && st.qualify && progressionOf(st).mode === "qualifiers" ? (() => {
        const t = effectiveTransition(st, prev);
        const poolCount = prev.kind === "pools" ? prev.pools ?? 1 : 1;
        const errs = transitionIssues(t, poolCount).filter((i) => i.level === "error");
        if (errs.length) throw new IntegrityError("transition", `${d.label} · ${st.name}: ${errs.map((e) => e.message).join("; ")}`);
        return { ...t, source_stage_id: ids.stage[`${d.divisionId}/${prev.id}`] ?? null, destination_stage_key: st.id };
      })() : null;
      row ??= (await db.insert("tournament_stages", [{ tournament_id: tid, division_id: div.id, spec_key: st.id, label: st.name, kind: st.kind, stage_order: st.order, generation: st.generation ?? "owner_approval", config: { pools: st.pools, poolSize: st.poolSize, drawSize: st.drawSize, swissRounds: st.swissRounds, qualify: st.qualify, transition: tr, schedule: rawSchedule(st) } }]))[0];
      const sk = `${d.divisionId}/${st.id}`;
      ids.stage[sk] = row.id; ids.stageKind[sk] = st.kind;
      if (st.kind === "pools") for (let i = 0; i < (st.pools ?? 1); i++) {
        let [p] = await db.select("tournament_pools", { stage_id: row.id, pool_index: i });
        p ??= (await db.insert("tournament_pools", [{ tournament_id: tid, stage_id: row.id, pool_index: i, label: d.poolLabels?.[i] || poolDefaultLabel(i) }]))[0];
        ids.pool[`${sk}/${i}`] = p.id;
      }
    }
  }
  return ids;
}

/** Hierarchy view of the spec (engine keys) used for identity validation before any insert. */
export function hierarchyFromSpec(tid: string, spec: TournamentSpec): HTournament {
  return {
    id: tid, kind: "tournament", label: spec.name,
    divisions: spec.divisions.map((d) => ({
      id: d.divisionId, kind: "division", label: d.label,
      stages: d.stages.map((s) => ({
        id: s.id, kind: "stage", stageKind: s.kind, label: s.name,
        pools: s.kind === "pools" ? Array.from({ length: s.pools ?? 1 }, (_, i) => ({ id: `${d.divisionId}:${s.id}:pool${i + 1}`, kind: "pool" as const, label: poolDefaultLabel(i), format: "round_robin" as StageKind, scoring: "", qualifyPerPool: null })) : [],
      })),
    })),
  };
}

const splitUnit = (id: string | null) => (id ? id.split("+") : [null, null]);
const legacyStage = (k: StageKind) => (k === "knockout" || k === "placement" ? "ko" : "group");

/** Validate then insert rounds + matches for engine fixtures. Nothing is written if validation fails. */
export async function insertFixtures(db: Db, tid: string, spec: TournamentSpec, ids: StructureIds, fixtures: EngineFixture[], existing: FixtureRow[] = []) {
  assertFixtureIdentity(hierarchyFromSpec(tid, spec), fixtures);
  assertNoReentry([...existing, ...fixtures]);
  for (const d of spec.divisions) {
    const ents = new Set(d.entrants.map((e) => e.id));
    for (const f of fixtures.filter((x) => x.divisionId === d.divisionId))
      for (const u of [f.a, f.b]) if (u && !ents.has(u)) throw new IntegrityError("cross_division", `${u} is not an entrant of ${d.label}.`);
  }
  // Courts: only the tournament's selected court records (Design venue pool). Never invent one.
  if (fixtures.some((f) => f.courtId != null)) {
    const venues = await db.select("tournament_venues", { tournament_id: tid });
    const pool = new Set<number>(venues.flatMap((v) => (v.court_ids ?? []) as number[]));
    const bad = fixtures.find((f) => f.courtId != null && !pool.has(f.courtId));
    if (bad) throw new IntegrityError("court_not_selected", `Court ${bad.courtId} is not one of the tournament's selected courts.`);
  }
  const roundIds: Record<string, string> = {};
  const [firstDiv] = spec.divisions;
  for (const f of fixtures) {
    const key = `${f.divisionId}/${f.stageId}/${f.roundId}`;
    if (roundIds[key]) continue;
    const sk = `${f.divisionId}/${f.stageId}`;
    const [r] = await db.insert("club_champs_rounds", [{
      champ_id: tid, group_number: spec.divisions.findIndex((d) => d.divisionId === f.divisionId) + 1, round_number: f.round ?? 1,
      division_id: ids.division[f.divisionId], stage_id: ids.stage[sk], stage_key: f.stageId,
      round_type: legacyStage(f.stageKind) === "ko" ? "knockout" : f.stageKind === "swiss" ? "swiss" : "round_robin", label: `Round ${f.round ?? 1}`, status: "active",
    }]);
    roundIds[key] = r.id;
  }
  void firstDiv;
  // Fixed-date stages: every game inherits its round's date (times/courts are set later).
  const roundDate = (f: EngineFixture): string | null => {
    const st = spec.divisions.find((d) => d.divisionId === f.divisionId)?.stages.find((s) => s.id === f.stageId);
    const sch = st?.schedule as any;
    if (!sch || sch.rule !== "fixed") return null;
    const d = (sch.roundDates ?? [])[(f.round ?? 1) - 1] ?? ((f.round ?? 1) === 1 ? sch.date : null);
    return d ? String(d).slice(0, 10) : null;
  };
  // Knockout rounds carry their real name (QF/SF/Final) so result messages and member pages
  // recognise the final. Named from the number of games in that round of the draw.
  const koCount = new Map<string, number>();
  for (const f of fixtures) if (legacyStage(f.stageKind) === "ko" && !f.thirdPlace) {
    const k = `${f.divisionId}/${f.stageId}/${f.round ?? 1}`;
    koCount.set(k, (koCount.get(k) ?? 0) + 1);
  }
  const koName = (n: number) => (n <= 1 ? "Final" : n === 2 ? "Semi-final" : n <= 4 ? "Quarter-final" : `Round of ${Math.pow(2, Math.ceil(Math.log2(n * 2)))}`);
  const rows = fixtures.map((f) => {
    const sk = `${f.divisionId}/${f.stageId}`;
    const date = roundDate(f);
    const koLabel = legacyStage(f.stageKind) === "ko" && !f.thirdPlace ? koName(koCount.get(`${f.divisionId}/${f.stageId}/${f.round ?? 1}`) ?? 1) : null;
    const poolIdx = f.poolId ? Number(/pool(\d+)$/.exec(f.poolId)![1]) - 1 : null;
    const [a1, a2] = splitUnit(f.a); const [b1, b2] = splitUnit(f.b);
    return {
      champ_id: tid, group_number: spec.divisions.findIndex((d) => d.divisionId === f.divisionId) + 1,
      round_number: f.round ?? 1, stage: legacyStage(f.stageKind), stage_key: f.stageId, status: "scheduled",
      player_a_member_id: a1, partner_a_member_id: a2, player_b_member_id: b1, partner_b_member_id: b2,
      pool_number: poolIdx == null ? null : poolIdx + 1, bracket_position: f.slot ?? null,
      ...(f.thirdPlace ? { stage_label: "3rd place" } : koLabel ? { stage_label: koLabel } : f.label ? { stage_label: f.label } : {}),
      division_id: ids.division[f.divisionId], stage_id: ids.stage[sk],
      pool_id: poolIdx == null ? null : ids.pool[`${sk}/${poolIdx}`] ?? (() => { throw new IntegrityError("no_pool", "Pool not persisted."); })(),
      round_id: roundIds[`${f.divisionId}/${f.stageId}/${f.roundId}`],
      ...(f.courtId != null ? { court_id: f.courtId } : {}),
      ...(date ? { scheduled_date: date } : {}),
    };
  });
  if (rows.some((r) => !r.division_id || !r.stage_id || !r.round_id)) throw new IntegrityError("identity", "Structural identity unresolved.");
  return db.insert("club_champs_matches", rows);
}

/** Load entrants for each division from club_champs_entries (group_number = division order + 1). */
export async function loadEntrants(db: Db, tid: string, rawSpec: TournamentSpec): Promise<TournamentSpec> {
  // Dates come from ONE place: the tournament row. Inheriting stages are resolved here, never stored.
  const [tour] = await db.select("tournaments", { id: tid });
  const tw = { start: tour?.start_date ?? null, end: tour?.end_date ?? null };
  const dateErr = specDateIssues(rawSpec, tw)[0];
  if (dateErr) throw new IntegrityError(dateErr.code, dateErr.message);
  const spec = resolveSpecDates(rawSpec, tw);
  const rows = await db.select("club_champs_entries", { champ_id: tid });
  return {
    ...spec,
    divisions: spec.divisions.map((d, i) => ({
      ...d,
      entrants: rows.filter((r) => r.group_number === i + 1).sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0))
        .map((r, k) => ({ id: r.partner_member_id ? `${r.club_member_id}+${r.partner_member_id}` : r.club_member_id, rank: r.order_index != null ? k + 1 : null })),
      expectedEntrants: d.expectedEntrants ?? rows.filter((r) => r.group_number === i + 1).length,
    })),
  };
}

/** Full first-stage generation for a structured tournament. */
export async function generateStructuredTournament(db: Db, tid: string) {
  const [t] = await db.select("tournaments", { id: tid });
  if (t?.builder_architecture !== "structured" || !t.builder_spec) throw new IntegrityError("not_structured", "Tournament has no structured specification.");
  const existing = await db.select("club_champs_matches", { champ_id: tid });
  if (existing.length) throw new IntegrityError("exists", "Games already exist. Use rebuild instead.");
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  for (const d of spec.divisions) {
    const errs = contractIssues(d).filter((i) => i.level === "error");
    if (errs.length) throw new IntegrityError("contract", `${d.label}: ${errs.map((e) => e.message).join("; ")}`);
    if (d.entrants.length < 2) throw new IntegrityError("entrants", `${d.label}: needs at least 2 entries before games can be generated.`);
  }
  const ids = await persistStructure(db, tid, spec);
  const fixtures = generateFromSpec(spec, tid);
  return insertFixtures(db, tid, spec, ids, fixtures);
}

/* ───── playoffs from persisted structure ───── */

/** Pool standings from completed games of one pool stage. Ties at a qualifying boundary block (owner decision). */
export function poolStandings(divisionKey: string, stageKey: string, matches: Array<Record<string, any>>, perPool: number): PoolStanding[] {
  const unitOf = (m: Record<string, any>, side: "a" | "b") => {
    const p = m[`player_${side}_member_id`], q = m[`partner_${side}_member_id`];
    return q ? `${p}+${q}` : p;
  };
  const byPool = new Map<number, Map<string, number>>();
  // A one-field round robin has no pool number: treat it as a single pool.
  for (const m of matches.filter((x) => x.stage_key === stageKey)) {
    const pn = m.pool_number ?? 1;
    const pool = byPool.get(pn) ?? new Map<string, number>();
    byPool.set(pn, pool);
    const a = unitOf(m, "a"), b = unitOf(m, "b");
    for (const u of [a, b]) if (u && !pool.has(u)) pool.set(u, 0);
    if (m.winner_member_id) {
      const w = String(a).split("+").includes(m.winner_member_id) ? a : b;
      pool.set(w, (pool.get(w) ?? 0) + 1);
    }
  }
  const out: PoolStanding[] = [];
  for (const [pool, tally] of [...byPool.entries()].sort((x, y) => x[0] - y[0])) {
    rankPoolTally(tally, perPool, `Pool ${pool}`).forEach((id, i) => out.push({ pool, position: i + 1, id, divisionId: divisionKey }));
  }
  return out;
}

export const toFixtureRow = (divisionKey: string, m: Record<string, any>, kind: StageKind): FixtureRow => ({
  id: m.id, divisionId: divisionKey, stageId: m.stage_key, stageKind: kind, round: m.round_number,
  a: m.partner_a_member_id ? `${m.player_a_member_id}+${m.partner_a_member_id}` : m.player_a_member_id,
  b: m.partner_b_member_id ? `${m.player_b_member_id}+${m.partner_b_member_id}` : m.player_b_member_id,
  status: m.status, score: m.score, pool: m.pool_number ?? null, thirdPlace: m.stage_label === "3rd place" || undefined, ...({ slot: m.bracket_position } as object),
  winner: !m.winner_member_id ? null
    : [m.player_a_member_id, m.partner_a_member_id].includes(m.winner_member_id)
      ? (m.partner_a_member_id ? `${m.player_a_member_id}+${m.partner_a_member_id}` : m.player_a_member_id)
      : (m.partner_b_member_id ? `${m.player_b_member_id}+${m.partner_b_member_id}` : m.player_b_member_id),
});

export async function previewStructuredPlayoffs(db: Db, tid: string, divisionKey: string, stageKey: string): Promise<PlayoffPreview> {
  const [t] = await db.select("tournaments", { id: tid });
  const spec = t.builder_spec as TournamentSpec;
  const d = spec.divisions.find((x) => x.divisionId === divisionKey);
  if (!d) throw new IntegrityError("no_division", "Unknown division.");
  const stage = d.stages.find((s) => s.id === stageKey)!;
  const src = d.stages.find((s) => s.order === stage.order - 1)!;
  const gi = spec.divisions.indexOf(d) + 1;
  const matches = (await db.select("club_champs_matches", { champ_id: tid })).filter((m) => m.group_number === gi);
  const kindOf = (k: string) => d.stages.find((s) => s.id === k)?.kind ?? "round_robin";
  const existing = matches.map((m) => toFixtureRow(divisionKey, m, kindOf(m.stage_key)));
  const { transition, slots } = previewTransition(d, stageKey);
  const notReady = (reason: string): PlayoffPreview => ({
    ok: false, reason, stage, slots, transition, poolLabels: d.poolLabels, resolved: false,
    qualifiers: slots.map((p) => ({ slot: p.slot, a: null, b: null, aSlot: p.a, bSlot: p.b })),
  });
  const srcDone = existing.filter((f) => f.stageId === src.id);
  if (!srcDone.length || !srcDone.every(isDecided)) return notReady(`${src.name} is not finished.`);
  if (src.kind === "swiss" && Math.max(...srcDone.map((f) => f.round ?? 1)) < (src.swissRounds ?? 1)) return notReady(`${src.name}: not all Swiss rounds are played yet.`);
  const cut = Math.max(0, ...transition.positions);
  const standings = poolStandings(divisionKey, src.id, matches, cut);
  return previewPlayoffs(d, stageKey, standings, existing);
}

export async function confirmStructuredPlayoffs(db: Db, tid: string, divisionKey: string, stageKey: string, ownerConfirmed: boolean) {
  const preview = await previewStructuredPlayoffs(db, tid, divisionKey, stageKey);
  const [t] = await db.select("tournaments", { id: tid });
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  const d = spec.divisions.find((x) => x.divisionId === divisionKey)!;
  const gi = spec.divisions.indexOf(d) + 1;
  const matches = (await db.select("club_champs_matches", { champ_id: tid })).filter((m) => m.group_number === gi);
  const existing = matches.map((m) => toFixtureRow(divisionKey, m, d.stages.find((s) => s.id === m.stage_key)?.kind ?? "round_robin"));
  const rows = confirmPlayoffs(tid, d, preview, { ownerConfirmed, existing });
  const ids = await persistStructure(db, tid, spec);
  return insertFixtures(db, tid, spec, ids, rows, existing);
}

/** Next knockout round (QF → SF → Final) inside the SAME knockout stage; pool stays NULL. */
export function nextKnockoutRound(tid: string, divisionKey: string, stageKey: string, rows: FixtureRow[], opts?: { thirdPlace?: boolean }): EngineFixture[] {
  const ko = rows.filter((f) => f.divisionId === divisionKey && f.stageId === stageKey);
  if (!ko.length) throw new IntegrityError("no_stage_rows", "Knockout stage has no games yet.");
  if (ko.some((f) => f.stageKind !== "knockout")) throw new IntegrityError("stage_kind", "Only knockout stages advance by rounds.");
  const last = Math.max(...ko.map((f) => f.round ?? 1));
  const cur = ko.filter((f) => (f.round ?? 1) === last && !f.thirdPlace).sort((a, b) => ((a as any).slot ?? 0) - ((b as any).slot ?? 0));
  if (cur.length < 2) throw new IntegrityError("final_done", "The final has already been generated.");
  if (!cur.every((f) => f.winner || !f.a || !f.b)) throw new IntegrityError("prereq", "Current round is not finished.");
  const win = (f: FixtureRow) => f.winner ?? f.a ?? f.b;
  const next: EngineFixture[] = [];
  for (let i = 0; i < cur.length; i += 2) next.push({
    tournamentId: tid, divisionId: divisionKey, stageId: stageKey, stageKind: "knockout",
    roundId: `${stageKey}:r${last + 1}`, round: last + 1, poolId: null, slot: i / 2 + 1, a: win(cur[i]), b: win(cur[i + 1]),
  });
  // 3rd/4th place: when the final is created from two semi-finals, the two losers play off.
  if (cur.length === 2 && opts?.thirdPlace) {
    const lose = (f: FixtureRow) => (f.a && f.b ? (f.winner === f.a ? f.b : f.a) : null);
    const [l1, l2] = [lose(cur[0]), lose(cur[1])];
    if (l1 && l2) next.push({ tournamentId: tid, divisionId: divisionKey, stageId: stageKey, stageKind: "knockout", roundId: `${stageKey}:r${last + 1}`, round: last + 1, poolId: null, slot: 2, a: l1, b: l2, thirdPlace: true });
  }
  assertNoReentry([...ko, ...next]);
  return next;
}

/* ───── rebuild + withdrawal on the structured model ───── */

export interface RebuildReport { regenerated: string[]; removedFuture: number; created: number; keptPlayed: number }

/**
 * Rebuild from CURRENT entrants and saved spec.
 * - Division with no played games: its unplayed games are replaced by a fresh generation.
 * - Division with played games: results are kept; only unplayed games involving entrants
 *   who are no longer in the event are removed (withdrawal). Nothing is re-paired.
 */
export async function rebuildStructured(db: Db, tid: string): Promise<RebuildReport> {
  if (!db.remove) throw new IntegrityError("unsupported", "This database cannot remove rows.");
  const [t] = await db.select("tournaments", { id: tid });
  if (t?.builder_architecture !== "structured" || !t.builder_spec) throw new IntegrityError("not_structured", "Tournament has no structured specification.");
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  const ids = await persistStructure(db, tid, spec);
  const all = await db.select("club_champs_matches", { champ_id: tid });
  const report: RebuildReport = { regenerated: [], removedFuture: 0, created: 0, keptPlayed: 0 };
  for (const [i, d] of spec.divisions.entries()) {
    const rows = all.filter((m) => m.group_number === i + 1);
    const fx = rows.map((m) => toFixtureRow(d.divisionId, m, d.stages.find((s) => s.id === m.stage_key)?.kind ?? "round_robin"));
    const played = fx.filter((f) => isDecided(f) || ["in_progress", "live"].includes(String(f.status ?? "").toLowerCase()));
    report.keptPlayed += played.length;
    if (!played.length) {
      const errs = contractIssues(d).filter((x) => x.level === "error");
      if (errs.length) throw new IntegrityError("contract", `${d.label}: ${errs.map((e) => e.message).join("; ")}`);
      await db.remove("club_champs_matches", rows.map((r) => r.id));
      report.removedFuture += rows.length;
      if (d.entrants.length >= 2) {
        const created = generateFromSpec({ ...spec, divisions: [d] }, tid);
        await insertFixtures(db, tid, spec, ids, created);
        report.created += created.length;
      }
      report.regenerated.push(d.label);
    } else {
      const members = new Set(d.entrants.flatMap((e) => e.id.split("+")));
      const gone = (u: string | null) => !!u && u.split("+").some((p) => !members.has(p));
      const drop = fx.filter((f) => !played.includes(f) && (gone(f.a) || gone(f.b))).map((f) => f.id!);
      await db.remove("club_champs_matches", drop);
      report.removedFuture += drop.length;
    }
  }
  return report;
}

/** Withdraw one player (and their pair) then rebuild. Played results stay; only their future games go. */
export async function withdrawStructured(db: Db, tid: string, memberId: string): Promise<RebuildReport> {
  if (!db.remove) throw new IntegrityError("unsupported", "This database cannot remove rows.");
  const entries = (await db.select("club_champs_entries", { champ_id: tid })).filter((e) => e.club_member_id === memberId || e.partner_member_id === memberId);
  if (!entries.length) throw new IntegrityError("not_entered", "That player is not entered.");
  await db.remove("club_champs_entries", entries.map((e) => e.id));
  return rebuildStructured(db, tid);
}

/** Start the next stage when everyone continues or pairs are formed. Qualifier stages use confirmStructuredPlayoffs. */
export async function startNextStructuredStage(db: Db, tid: string, divisionKey: string, stageKey: string, opts: { ownerConfirmed: boolean; pairs?: string[][] }) {
  const [t] = await db.select("tournaments", { id: tid });
  if (t?.builder_architecture !== "structured") throw new IntegrityError("not_structured", "Tournament has no structured specification.");
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  const d = spec.divisions.find((x) => x.divisionId === divisionKey);
  if (!d) throw new IntegrityError("no_division", "Unknown division.");
  const gi = spec.divisions.indexOf(d) + 1;
  const matches = (await db.select("club_champs_matches", { champ_id: tid })).filter((m) => m.group_number === gi);
  const existing = matches.map((m) => toFixtureRow(divisionKey, m, d.stages.find((s) => s.id === m.stage_key)?.kind ?? "round_robin"));
  const target = d.stages.find((s) => s.id === stageKey);
  if (target?.kind === "mapped") return startMappedStage(db, tid, spec, d, target, matches, existing, opts.ownerConfirmed);
  const plan = nextStageFixtures(tid, d, stageKey, existing, opts);
  // New pair units are valid entrants of this division for this stage only.
  const known = new Set(d.entrants.map((e) => e.id));
  const withUnits: TournamentSpec = { ...spec, divisions: spec.divisions.map((x) => x === d ? { ...x, entrants: [...x.entrants, ...plan.entrants.filter((e) => !known.has(e.id))] } : x) };
  const ids = await persistStructure(db, tid, withUnits);
  return insertFixtures(db, tid, withUnits, ids, plan.fixtures, existing);
}

/** Mapped stage fed by finishing positions of an earlier pool stage: positions → units → fixtures. */
async function startMappedStage(db: Db, tid: string, spec: TournamentSpec, d: SpecDivision, st: PlannedStage, matches: Array<Record<string, any>>, existing: FixtureRow[], ownerConfirmed: boolean) {
  const m = st.mapping;
  if (!m || m.source !== "stage_standings") throw new IntegrityError("mapping_source", `${st.name}: its games were created with the tournament.`);
  if (existing.some((f) => f.stageId === st.id)) throw new IntegrityError("exists", `${st.name} already has games.`);
  if (st.generation !== "automatic" && !ownerConfirmed) throw new IntegrityError("needs_confirmation", "Owner must confirm before the next stage is created.");
  const src = d.stages.find((s) => s.id === m.sourceStageId);
  if (!src) throw new IntegrityError("mapping_source", `${st.name}: source stage not found.`);
  const done = existing.filter((f) => f.stageId === src.id);
  if (!done.length || !done.every(isDecided)) throw new IntegrityError("prereq", `${src.name} is not finished.`);
  // Every position used must be decided; a tie at any used position blocks (owner decides, never invented).
  const standings = poolStandings(d.divisionId, src.id, matches, m.poolSize);
  const wins = new Map<string, number>();
  for (const x of matches.filter((r) => r.stage_key === src.id && r.winner_member_id)) {
    const a = x.partner_a_member_id ? `${x.player_a_member_id}+${x.partner_a_member_id}` : x.player_a_member_id;
    const b = x.partner_b_member_id ? `${x.player_b_member_id}+${x.partner_b_member_id}` : x.player_b_member_id;
    const w = String(a).split("+").includes(x.winner_member_id) ? a : b;
    wins.set(w, (wins.get(w) ?? 0) + 1);
  }
  const used = new Set(m.units.flatMap((u) => u.slots.map((s) => `${s.pool + 1}:${s.position}`)));
  for (const s of standings) {
    const next = standings.find((o) => o.pool === s.pool && o.position === s.position + 1);
    if (next && (used.has(`${s.pool}:${s.position}`) || used.has(`${s.pool}:${s.position + 1}`)) && (wins.get(s.id) ?? 0) === (wins.get(next.id) ?? 0))
      throw new IntegrityError("tie", `${d.poolLabels?.[s.pool - 1] ?? `Pool ${s.pool}`}: positions ${s.position} and ${s.position + 1} are tied — the owner must decide the order before pairs/matchups are formed.`);
  }
  const positions: string[][] = Array.from({ length: m.pools }, () => []);
  for (const s of standings) positions[s.pool - 1][s.position - 1] = s.id;
  const fixtures = mappedFixtures(tid, d, st, positions);
  const known = new Set(d.entrants.map((e) => e.id));
  const units = [...new Set(fixtures.flatMap((f) => [f.a!, f.b!]))].filter((u) => !known.has(u)).map((id) => ({ id, rank: null }));
  const withUnits: TournamentSpec = { ...spec, divisions: spec.divisions.map((x) => x === d ? { ...x, entrants: [...x.entrants, ...units] } : x) };
  const ids = await persistStructure(db, tid, withUnits);
  return insertFixtures(db, tid, withUnits, ids, fixtures, existing);
}
