/**
 * Structured (Beta) tournament persistence + generation.
 * Order is fixed: spec → validate → persist divisions/stages/pools → rounds → fixtures
 * against those ids → identity validation → insert. Legacy tournaments never come here.
 * The DB trigger `guard_structured_match_identity` enforces the same identity rules.
 */
import { IntegrityError, assertNoReentry, contractIssues, isDecided, type FixtureRow, type PlannedStage, type PoolStanding, type StageKind } from "./contract";
import { assertFixtureIdentity, poolDefaultLabel, type HTournament } from "./hierarchy";
import { confirmPlayoffs, generateFromSpec, previewPlayoffs, type EngineFixture, type PlayoffPreview, type SpecDivision, type TournamentSpec } from "./engine-service";
import type { TournamentDefinition } from "../smart-builder/definition";

/* ───── spec from the Beta definition ───── */

export function specFromDefinition(def: TournamentDefinition): TournamentSpec {
  return {
    version: 1, architecture: "structured", name: def.name,
    scope: (def as any).event ?? null,
    divisions: def.divisions.map((d) => {
      const stages: PlannedStage[] = [];
      d.sections.forEach((sec) => sec.stages.forEach((st) => {
        let kind: StageKind;
        if (st.kind === "round_robin") kind = st.groups > 1 ? "pools" : "round_robin";
        else if (st.kind === "knockout" || st.kind === "swiss" || st.kind === "placement") kind = st.kind as StageKind;
        else throw new IntegrityError("unsupported_stage", `${d.name} · ${st.name}: this stage type can't be generated by the structured engine yet.`);
        const prev = stages[stages.length - 1];
        const s = st.schedule ?? { mode: "unset" };
        stages.push({
          id: st.id, order: stages.length, kind, name: st.name,
          pools: kind === "pools" ? st.groups : undefined,
          poolSize: st.groupSize ?? undefined,
          swissRounds: st.swissRounds ?? undefined,
          drawSize: kind === "knockout" ? st.groupSize ?? undefined : undefined,
          schedule: {
            rule: s.mode === "fixed" ? "fixed" : s.mode === "play_by" ? "play_by" : s.mode === "window" ? "window" : null,
            date: (s as any).roundDates?.[0] ?? (s as any).startDate ?? null,
            deadline: (s as any).endDate ?? null, start: (s as any).startDate ?? null, end: (s as any).endDate ?? null,
          },
          qualify: prev ? { perPool: (def.divisions.flatMap((x) => x.sections.flatMap((y) => y.stages)).find((x) => x.id === prev.id)?.advance?.perGroup) ?? 0, mapping: st.qualifierMapping ?? null } : null,
          generation: st.generation ?? (prev ? "owner_approval" : undefined),
        });
      }));
      return {
        divisionId: d.id, label: d.name, unit: d.entry === "pairs" ? "pairs" : "players",
        expectedEntrants: d.sections[0]?.stages[0]?.input?.entrants ?? null,
        seeding: { source: (def as any).event?.seedingSource ?? "entry_order", method: "snake" },
        placements: "champion", stages, entrants: [], poolLabels: d.poolLabels,
      } satisfies SpecDivision;
    }),
  };
}

/* ───── db access (injected so tests can use an in-memory fake) ───── */

export interface Db {
  insert(table: string, rows: Record<string, unknown>[]): Promise<Array<Record<string, any>>>;
  select(table: string, filter: Record<string, unknown>): Promise<Array<Record<string, any>>>;
  update(table: string, filter: Record<string, unknown>, patch: Record<string, unknown>): Promise<void>;
}

export interface StructureIds {
  division: Record<string, string>;
  stage: Record<string, string>; // `${divKey}/${stageKey}`
  pool: Record<string, string>; // `${divKey}/${stageKey}/${index}`
  stageKind: Record<string, StageKind>;
}

/** Persist divisions → stages → pools. Idempotent: re-uses existing rows by spec_key. */
export async function persistStructure(db: Db, tid: string, spec: TournamentSpec): Promise<StructureIds> {
  const ids: StructureIds = { division: {}, stage: {}, pool: {}, stageKind: {} };
  const [tour] = await db.select("tournaments", { id: tid });
  if (tour?.builder_architecture !== "structured") throw new IntegrityError("not_structured", "Only structured (Beta) tournaments use this path.");
  for (const [di, d] of spec.divisions.entries()) {
    let [div] = await db.select("tournament_divisions", { tournament_id: tid, spec_key: d.divisionId });
    div ??= (await db.insert("tournament_divisions", [{ tournament_id: tid, spec_key: d.divisionId, label: d.label, unit: d.unit, sort_order: di }]))[0];
    ids.division[d.divisionId] = div.id;
    for (const st of d.stages) {
      let [row] = await db.select("tournament_stages", { division_id: div.id, spec_key: st.id });
      row ??= (await db.insert("tournament_stages", [{ tournament_id: tid, division_id: div.id, spec_key: st.id, label: st.name, kind: st.kind, stage_order: st.order, generation: st.generation ?? "owner_approval", config: { pools: st.pools, poolSize: st.poolSize, drawSize: st.drawSize, swissRounds: st.swissRounds, qualify: st.qualify, schedule: st.schedule } }]))[0];
      const sk = `${d.divisionId}/${st.id}`;
      ids.stage[sk] = row.id; ids.stageKind[sk] = st.kind;
      if (st.kind === "pools") for (let i = 0; i < (st.pools ?? 1); i++) {
        let [p] = await db.select("tournament_pools", { stage_id: row.id, pool_index: i });
        p ??= (await db.insert("tournament_pools", [{ tournament_id: tid, stage_id: row.id, pool_index: i, label: d.poolLabels?.[i] || poolDefaultLabel(i) }]))[0];
        ids.pool[`${sk}/${i}`] = p.id;
      }
    }
  }
  return ids;
}

/** Hierarchy view of the spec (engine keys) used for identity validation before any insert. */
export function hierarchyFromSpec(tid: string, spec: TournamentSpec): HTournament {
  return {
    id: tid, kind: "tournament", label: spec.name,
    divisions: spec.divisions.map((d) => ({
      id: d.divisionId, kind: "division", label: d.label,
      stages: d.stages.map((s) => ({
        id: s.id, kind: "stage", stageKind: s.kind, label: s.name,
        pools: s.kind === "pools" ? Array.from({ length: s.pools ?? 1 }, (_, i) => ({ id: `${d.divisionId}:${s.id}:pool${i + 1}`, kind: "pool" as const, label: poolDefaultLabel(i), format: "round_robin" as StageKind, scoring: "", qualifyPerPool: null })) : [],
      })),
    })),
  };
}

const splitUnit = (id: string | null) => (id ? id.split("+") : [null, null]);
const legacyStage = (k: StageKind) => (k === "knockout" || k === "placement" ? "ko" : "group");

/** Validate then insert rounds + matches for engine fixtures. Nothing is written if validation fails. */
export async function insertFixtures(db: Db, tid: string, spec: TournamentSpec, ids: StructureIds, fixtures: EngineFixture[], existing: FixtureRow[] = []) {
  assertFixtureIdentity(hierarchyFromSpec(tid, spec), fixtures);
  assertNoReentry([...existing, ...fixtures]);
  for (const d of spec.divisions) {
    const ents = new Set(d.entrants.map((e) => e.id));
    for (const f of fixtures.filter((x) => x.divisionId === d.divisionId))
      for (const u of [f.a, f.b]) if (u && !ents.has(u)) throw new IntegrityError("cross_division", `${u} is not an entrant of ${d.label}.`);
  }
  const roundIds: Record<string, string> = {};
  const [firstDiv] = spec.divisions;
  for (const f of fixtures) {
    const key = `${f.divisionId}/${f.stageId}/${f.roundId}`;
    if (roundIds[key]) continue;
    const sk = `${f.divisionId}/${f.stageId}`;
    const [r] = await db.insert("club_champs_rounds", [{
      champ_id: tid, group_number: spec.divisions.findIndex((d) => d.divisionId === f.divisionId) + 1, round_number: f.round ?? 1,
      division_id: ids.division[f.divisionId], stage_id: ids.stage[sk], stage_key: f.stageId,
      round_type: legacyStage(f.stageKind) === "ko" ? "knockout" : "round_robin", label: `Round ${f.round ?? 1}`, status: "generated",
    }]);
    roundIds[key] = r.id;
  }
  void firstDiv;
  const rows = fixtures.map((f) => {
    const sk = `${f.divisionId}/${f.stageId}`;
    const poolIdx = f.poolId ? Number(f.poolId.split(":pool")[1]) - 1 : null;
    const [a1, a2] = splitUnit(f.a); const [b1, b2] = splitUnit(f.b);
    return {
      champ_id: tid, group_number: spec.divisions.findIndex((d) => d.divisionId === f.divisionId) + 1,
      round_number: f.round ?? 1, stage: legacyStage(f.stageKind), stage_key: f.stageId, status: "scheduled",
      player_a_member_id: a1, partner_a_member_id: a2, player_b_member_id: b1, partner_b_member_id: b2,
      pool_number: poolIdx == null ? null : poolIdx + 1, bracket_position: f.slot ?? null,
      division_id: ids.division[f.divisionId], stage_id: ids.stage[sk],
      pool_id: poolIdx == null ? null : ids.pool[`${sk}/${poolIdx}`] ?? (() => { throw new IntegrityError("no_pool", "Pool not persisted."); })(),
      round_id: roundIds[`${f.divisionId}/${f.stageId}/${f.roundId}`],
    };
  });
  if (rows.some((r) => !r.division_id || !r.stage_id || !r.round_id)) throw new IntegrityError("identity", "Structural identity unresolved.");
  return db.insert("club_champs_matches", rows);
}

/** Load entrants for each division from club_champs_entries (group_number = division order + 1). */
export async function loadEntrants(db: Db, tid: string, spec: TournamentSpec): Promise<TournamentSpec> {
  const rows = await db.select("club_champs_entries", { champ_id: tid });
  return {
    ...spec,
    divisions: spec.divisions.map((d, i) => ({
      ...d,
      entrants: rows.filter((r) => r.group_number === i + 1).sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0))
        .map((r, k) => ({ id: r.partner_member_id ? `${r.club_member_id}+${r.partner_member_id}` : r.club_member_id, rank: r.order_index != null ? k + 1 : null })),
      expectedEntrants: d.expectedEntrants ?? rows.filter((r) => r.group_number === i + 1).length,
    })),
  };
}

/** Full first-stage generation for a structured tournament. */
export async function generateStructuredTournament(db: Db, tid: string) {
  const [t] = await db.select("tournaments", { id: tid });
  if (t?.builder_architecture !== "structured" || !t.builder_spec) throw new IntegrityError("not_structured", "Tournament has no structured specification.");
  const existing = await db.select("club_champs_matches", { champ_id: tid });
  if (existing.length) throw new IntegrityError("exists", "Games already exist. Use rebuild instead.");
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  for (const d of spec.divisions) {
    const errs = contractIssues(d).filter((i) => i.level === "error");
    if (errs.length) throw new IntegrityError("contract", `${d.label}: ${errs.map((e) => e.message).join("; ")}`);
  }
  const ids = await persistStructure(db, tid, spec);
  const fixtures = generateFromSpec(spec, tid);
  return insertFixtures(db, tid, spec, ids, fixtures);
}

/* ───── playoffs from persisted structure ───── */

/** Pool standings from completed games of one pool stage. Ties at a qualifying boundary block (owner decision). */
export function poolStandings(divisionKey: string, stageKey: string, matches: Array<Record<string, any>>, perPool: number): PoolStanding[] {
  const unitOf = (m: Record<string, any>, side: "a" | "b") => {
    const p = m[`player_${side}_member_id`], q = m[`partner_${side}_member_id`];
    return q ? `${p}+${q}` : p;
  };
  const byPool = new Map<number, Map<string, number>>();
  for (const m of matches.filter((x) => x.stage_key === stageKey && x.pool_number != null)) {
    const pool = byPool.get(m.pool_number) ?? new Map<string, number>();
    byPool.set(m.pool_number, pool);
    const a = unitOf(m, "a"), b = unitOf(m, "b");
    for (const u of [a, b]) if (u && !pool.has(u)) pool.set(u, 0);
    if (m.winner_member_id) {
      const w = String(a).split("+").includes(m.winner_member_id) ? a : b;
      pool.set(w, (pool.get(w) ?? 0) + 1);
    }
  }
  const out: PoolStanding[] = [];
  for (const [pool, tally] of [...byPool.entries()].sort((x, y) => x[0] - y[0])) {
    const ranked = [...tally.entries()].sort((x, y) => y[1] - x[1]);
    if (ranked.length > perPool && ranked[perPool - 1][1] === ranked[perPool][1])
      throw new IntegrityError("tie", `Pool ${pool}: tie on the qualifying line needs an owner decision.`);
    ranked.forEach(([id], i) => out.push({ pool, position: i + 1, id, divisionId: divisionKey }));
  }
  return out;
}

const toFixtureRow = (divisionKey: string, m: Record<string, any>, kind: StageKind): FixtureRow => ({
  id: m.id, divisionId: divisionKey, stageId: m.stage_key, stageKind: kind, round: m.round_number,
  a: m.partner_a_member_id ? `${m.player_a_member_id}+${m.partner_a_member_id}` : m.player_a_member_id,
  b: m.partner_b_member_id ? `${m.player_b_member_id}+${m.partner_b_member_id}` : m.player_b_member_id,
  status: m.status, score: m.score,
  winner: !m.winner_member_id ? null
    : [m.player_a_member_id, m.partner_a_member_id].includes(m.winner_member_id)
      ? (m.partner_a_member_id ? `${m.player_a_member_id}+${m.partner_a_member_id}` : m.player_a_member_id)
      : (m.partner_b_member_id ? `${m.player_b_member_id}+${m.partner_b_member_id}` : m.player_b_member_id),
});

export async function previewStructuredPlayoffs(db: Db, tid: string, divisionKey: string, stageKey: string): Promise<PlayoffPreview> {
  const [t] = await db.select("tournaments", { id: tid });
  const spec = t.builder_spec as TournamentSpec;
  const d = spec.divisions.find((x) => x.divisionId === divisionKey);
  if (!d) throw new IntegrityError("no_division", "Unknown division.");
  const stage = d.stages.find((s) => s.id === stageKey)!;
  const src = d.stages.find((s) => s.order === stage.order - 1)!;
  const gi = spec.divisions.indexOf(d) + 1;
  const matches = (await db.select("club_champs_matches", { champ_id: tid })).filter((m) => m.group_number === gi);
  const kindOf = (k: string) => d.stages.find((s) => s.id === k)?.kind ?? "round_robin";
  const existing = matches.map((m) => toFixtureRow(divisionKey, m, kindOf(m.stage_key)));
  const srcDone = existing.filter((f) => f.stageId === src.id);
  if (!srcDone.length || !srcDone.every(isDecided)) return { ok: false, reason: `${src.name} is not finished.`, qualifiers: [], stage };
  const standings = poolStandings(divisionKey, src.id, matches, stage.qualify?.perPool ?? 0);
  return previewPlayoffs(d, stageKey, standings, existing);
}

export async function confirmStructuredPlayoffs(db: Db, tid: string, divisionKey: string, stageKey: string, ownerConfirmed: boolean) {
  const preview = await previewStructuredPlayoffs(db, tid, divisionKey, stageKey);
  const [t] = await db.select("tournaments", { id: tid });
  const spec = await loadEntrants(db, tid, t.builder_spec as TournamentSpec);
  const d = spec.divisions.find((x) => x.divisionId === divisionKey)!;
  const gi = spec.divisions.indexOf(d) + 1;
  const matches = (await db.select("club_champs_matches", { champ_id: tid })).filter((m) => m.group_number === gi);
  const existing = matches.map((m) => toFixtureRow(divisionKey, m, d.stages.find((s) => s.id === m.stage_key)?.kind ?? "round_robin"));
  const rows = confirmPlayoffs(tid, d, preview, { ownerConfirmed, existing });
  const ids = await persistStructure(db, tid, spec);
  return insertFixtures(db, tid, spec, ids, rows, existing);
}

/** Next knockout round (QF → SF → Final) inside the SAME knockout stage; pool stays NULL. */
export function nextKnockoutRound(tid: string, divisionKey: string, stageKey: string, rows: FixtureRow[]): EngineFixture[] {
  const ko = rows.filter((f) => f.divisionId === divisionKey && f.stageId === stageKey);
  if (!ko.length) throw new IntegrityError("no_stage_rows", "Knockout stage has no games yet.");
  if (ko.some((f) => f.stageKind !== "knockout")) throw new IntegrityError("stage_kind", "Only knockout stages advance by rounds.");
  const last = Math.max(...ko.map((f) => f.round ?? 1));
  const cur = ko.filter((f) => (f.round ?? 1) === last).sort((a, b) => ((a as any).slot ?? 0) - ((b as any).slot ?? 0));
  if (cur.length < 2) throw new IntegrityError("final_done", "The final has already been generated.");
  if (!cur.every((f) => f.winner || !f.a || !f.b)) throw new IntegrityError("prereq", "Current round is not finished.");
  const win = (f: FixtureRow) => f.winner ?? f.a ?? f.b;
  const next: EngineFixture[] = [];
  for (let i = 0; i < cur.length; i += 2) next.push({
    tournamentId: tid, divisionId: divisionKey, stageId: stageKey, stageKind: "knockout",
    roundId: `${stageKey}:r${last + 1}`, round: last + 1, poolId: null, slot: i / 2 + 1, a: win(cur[i]), b: win(cur[i + 1]),
  });
  assertNoReentry([...ko, ...next]);
  return next;
}
