import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Landmark, FileText, ExternalLink, Copy, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useMyClub } from "@/hooks/use-club";
import { ClubParticipationCard } from "@/components/club-admin/ClubParticipationCard";

interface Invoice {
  id: string;
  invoice_number: string;
  status: string;
  issued_at: string;
  due_date: string | null;
  paid_at: string | null;
  period_start: string;
  period_end: string;
  billing_cycle: string;
  plan_name: string;
  member_count: number;
  price_per_member: number;
  subtotal: number;
  vat_amount: number;
  total: number;
  currency: string;
}

const STATUS_COLORS: Record<string, string> = {
  paid: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300",
  open: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300",
  overdue: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300",
  void: "bg-muted text-muted-foreground",
  draft: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
};

const fmtMoney = (n: number, ccy = "ZAR") =>
  `${ccy === "ZAR" ? "R " : ccy + " "}${(n || 0).toFixed(2)}`;
const fmtDate = (d?: string | null) => (d ? new Date(d).toLocaleDateString() : "—");

export function SubscriptionTab({ clubId }: { clubId: string }) {
  const { data: myClub } = useMyClub();
  const club = myClub?.club;

  const { data: invoices = [], isLoading: invLoading } = useQuery({
    queryKey: ["club-platform-invoices", clubId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("platform_subscription_invoices")
        .select("*")
        .eq("club_id", clubId)
        .order("issued_at", { ascending: false });
      if (error) throw error;
      return (data || []) as Invoice[];
    },
  });

  const { data: bank } = useQuery({
    queryKey: ["platform-invoice-settings-public"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("app_settings")
        .select("value")
        .eq("key", "platform_invoice_settings")
        .maybeSingle();
      if (error && error.code !== "PGRST116") throw error;
      if (!data?.value) return null;
      try {
        return JSON.parse(data.value) as Record<string, string>;
      } catch {
        return null;
      }
    },
  });

  const outstanding = useMemo(
    () => invoices.filter((i) => i.status !== "paid" && i.status !== "void"),
    [invoices]
  );
  const totalOutstanding = outstanding.reduce((s, i) => s + Number(i.total || 0), 0);

  const copy = (text: string, label = "Copied") => {
    navigator.clipboard.writeText(text).then(
      () => toast.success(`${label} to clipboard`),
      () => toast.error("Copy failed")
    );
  };

  const handlePayStitch = (inv: Invoice) => {
    toast.info(
      "Stitch payment link will be generated by the platform. You'll receive it via email — or use EFT with the reference below."
    );
  };

  return (
    <div className="space-y-6 mt-4">
      {club && <ClubParticipationCard club={club} />}

      {/* Outstanding summary */}
      {outstanding.length > 0 && (
        <Card className="p-4 border-amber-300/60 bg-amber-50/60 dark:bg-amber-950/20">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <div>
              <h3 className="font-semibold text-sm">Outstanding subscription invoices</h3>
              <p className="text-xs text-muted-foreground">
                {outstanding.length} invoice{outstanding.length === 1 ? "" : "s"} awaiting payment
              </p>
            </div>
            <div className="text-right">
              <div className="text-[11px] uppercase tracking-wide text-muted-foreground">Total due</div>
              <div className="text-lg font-bold text-amber-800 dark:text-amber-300">
                {fmtMoney(totalOutstanding)}
              </div>
            </div>
          </div>
        </Card>
      )}

      {/* Invoice list */}
      <Card className="p-4 space-y-3">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" />
          <h3 className="font-semibold text-sm">Subscription Invoices</h3>
        </div>

        {invLoading ? (
          <div className="flex items-center gap-2 text-sm text-muted-foreground py-8 justify-center">
            <Loader2 className="w-4 h-4 animate-spin" /> Loading invoices…
          </div>
        ) : invoices.length === 0 ? (
          <div className="text-sm text-muted-foreground py-8 text-center border border-dashed rounded-md">
            No invoices yet. Invoices are generated by the platform once your subscription begins.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Invoice #</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead className="text-right">Members</TableHead>
                  <TableHead className="text-right">Total</TableHead>
                  <TableHead>Due</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {invoices.map((inv) => {
                  const unpaid = inv.status !== "paid" && inv.status !== "void";
                  return (
                    <TableRow key={inv.id}>
                      <TableCell className="font-mono text-xs">{inv.invoice_number}</TableCell>
                      <TableCell className="text-xs">
                        {fmtDate(inv.period_start)} → {fmtDate(inv.period_end)}
                        <div className="text-[10px] uppercase text-muted-foreground">
                          {inv.billing_cycle}
                        </div>
                      </TableCell>
                      <TableCell className="text-right text-xs">{inv.member_count}</TableCell>
                      <TableCell className="text-right font-semibold text-xs">
                        {fmtMoney(Number(inv.total), inv.currency)}
                      </TableCell>
                      <TableCell className="text-xs">{fmtDate(inv.due_date)}</TableCell>
                      <TableCell>
                        <Badge className={STATUS_COLORS[inv.status] || ""} variant="secondary">
                          {inv.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex gap-1 justify-end">
                          {unpaid && (
                            <Button
                              size="sm"
                              variant="default"
                              className="h-7 text-xs"
                              onClick={() => handlePayStitch(inv)}
                            >
                              <ExternalLink className="w-3 h-3 mr-1" /> Pay via Stitch
                            </Button>
                          )}
                          <Button
                            size="sm"
                            variant="outline"
                            className="h-7 text-xs"
                            onClick={() => copy(inv.invoice_number, "Invoice #")}
                          >
                            <Copy className="w-3 h-3" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        )}
      </Card>

      {/* EFT bank details */}
      <Card className="p-4 space-y-3">
        <div className="flex items-center gap-2">
          <Landmark className="w-4 h-4 text-primary" />
          <h3 className="font-semibold text-sm">EFT / Bank Payment Details</h3>
        </div>
        {!bank || !bank.bank_account_number ? (
          <p className="text-xs text-muted-foreground">
            Bank details have not been published yet. Please contact the platform administrator.
          </p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
            <BankRow label="Bank" value={bank.bank_name} onCopy={copy} />
            <BankRow label="Account Name" value={bank.bank_account_name} onCopy={copy} />
            <BankRow label="Account #" value={bank.bank_account_number} onCopy={copy} mono />
            <BankRow label="Branch Code" value={bank.bank_branch_code} onCopy={copy} mono />
            {bank.bank_swift && <BankRow label="SWIFT" value={bank.bank_swift} onCopy={copy} mono />}
            {bank.vat_number && <BankRow label="VAT #" value={bank.vat_number} onCopy={copy} mono />}
          </div>
        )}
        <p className="text-[11px] text-muted-foreground pt-1 border-t">
          Use your <strong>invoice number</strong> as the payment reference so we can allocate your
          EFT correctly.
        </p>
      </Card>
    </div>
  );
}

function BankRow({
  label,
  value,
  onCopy,
  mono,
}: {
  label: string;
  value?: string;
  onCopy: (v: string, label?: string) => void;
  mono?: boolean;
}) {
  if (!value) return null;
  return (
    <div className="flex items-center justify-between gap-2 rounded-md border bg-muted/30 px-3 py-2">
      <div className="min-w-0">
        <div className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</div>
        <div className={`text-sm ${mono ? "font-mono" : "font-medium"} truncate`}>{value}</div>
      </div>
      <Button size="sm" variant="ghost" className="h-7 px-2" onClick={() => onCopy(value, label)}>
        <Copy className="w-3 h-3" />
      </Button>
    </div>
  );
}
