// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function clientFor(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in SquashHub user's basic profile and club memberships.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: members }] = await Promise.all([
      supabase.from("profiles").select("id, first_name, last_name, email").eq("id", userId).maybeSingle(),
      supabase.from("club_members").select("id, club_id, first_name, last_name, role, ladder_position, clubs(name)").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      clubs: members ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-ladder.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_ladder_default = defineTool2({
  name: "get_ladder",
  title: "Get club ladder",
  description: "Return the current ladder standings for a SquashHub club. If no club_id is provided, the signed-in user's first club is used.",
  inputSchema: {
    club_id: z.string().uuid().optional().describe("Club UUID. Defaults to the user's club."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ club_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor2(ctx);
    let clubId = club_id;
    if (!clubId) {
      const { data: my } = await supabase.from("club_members").select("club_id").eq("user_id", ctx.getUserId()).limit(1).maybeSingle();
      clubId = my?.club_id;
    }
    if (!clubId) {
      return { content: [{ type: "text", text: "No club found for user." }], isError: true };
    }
    const { data, error } = await supabase.from("club_members").select("id, first_name, last_name, ladder_position, skill_rating, gender").eq("club_id", clubId).not("ladder_position", "is", null).order("ladder_position", { ascending: true }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ club_id: clubId, ladder: data }, null, 2) }],
      structuredContent: { club_id: clubId, ladder: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-bookings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_upcoming_bookings_default = defineTool3({
  name: "list_upcoming_bookings",
  title: "List upcoming bookings",
  description: "List the signed-in user's upcoming court bookings on SquashHub, ordered by start time.",
  inputSchema: {
    days_ahead: z2.number().int().min(1).max(90).optional().describe("How many days ahead to look (default 14)."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor3(ctx);
    const userId = ctx.getUserId();
    const now = /* @__PURE__ */ new Date();
    const until = new Date(now.getTime() + (days_ahead ?? 14) * 864e5);
    const { data, error } = await supabase.from("bookings").select("id, club_id, court_id, start_time, end_time, status, booked_by, opponent_name, courts(name)").eq("booked_by", userId).gte("start_time", now.toISOString()).lte("start_time", until.toISOString()).order("start_time", { ascending: true }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ bookings: data }, null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-matches.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_matches_default = defineTool4({
  name: "list_recent_matches",
  title: "List recent matches",
  description: "List the signed-in user's most recent SquashHub matches with scores and opponents.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor4(ctx);
    const userId = ctx.getUserId();
    const { data: members } = await supabase.from("club_members").select("id, club_id").eq("user_id", userId);
    const memberIds = (members ?? []).map((m) => m.id);
    if (memberIds.length === 0) {
      return {
        content: [{ type: "text", text: JSON.stringify({ matches: [] }) }],
        structuredContent: { matches: [] }
      };
    }
    const { data, error } = await supabase.from("matches").select("*").or(memberIds.map((id) => `player_a_id.eq.${id},player_b_id.eq.${id}`).join(",")).order("played_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ matches: data }, null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bzbuppwzljadulwntjys";
var mcp_default = defineMcp({
  name: "squashhub-mcp",
  title: "SquashHub",
  version: "0.1.0",
  instructions: "Tools for a SquashHub club: read the signed-in user's profile and clubs, view a club's ladder, list upcoming bookings, and list recent matches. All queries run under the user's row-level security scope.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, get_ladder_default, list_upcoming_bookings_default, list_recent_matches_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
