/**
 * What SquashHub's tournament engine can actually generate and run — a HARD constraint on the
 * Smart Builder. Design, validation, Review and Create (specFromDefinition) all read this one list,
 * so the builder can never accept a stage that only fails later at Review/Create.
 *
 * Pool-v-pool stages run on the engine's explicit-mapping stage ("mapped"): the qualification
 * source, pair formation and every matchup are structured data (see ./matchups and
 * ../tournaments/mapping), so they are supported whenever that mapping is complete and valid.
 */
import type { TournamentDefinition } from "./definition";
import { stageMappingIssues } from "./matchups";

/** Builder stage kinds the structured engine generates directly. */
export const ENGINE_KINDS = new Set(["round_robin", "knockout", "swiss", "placement", "cross_pool_league"]);
/** Bookkeeping steps: no games of their own. */
const STEP_KINDS = new Set(["pair_from_positions", "split"]);

export interface EngineVerdict {
  stageId: string;
  divisionName: string;
  stageName: string;
  state: "supported" | "unsupported";
  /** Plain explanation (why it can't run). */
  detail: string;
}

export function engineVerdicts(def: TournamentDefinition): EngineVerdict[] {
  const out: EngineVerdict[] = [];
  for (const d of def.divisions) for (const sec of d.sections) sec.stages.forEach((st, i) => {
    const base = { stageId: st.id, divisionName: d.name, stageName: st.name };
    if (STEP_KINDS.has(st.kind)) {
      out.push({ ...base, state: "unsupported", detail: `${d.name} · ${st.name}: this step type can't be generated by the tournament engine yet — use explicit matchups on the next stage instead.` });
      return;
    }
    if (st.kind === "cross_pool_league") {
      const issues = stageMappingIssues(d, st);
      out.push(issues.length ? { ...base, state: "unsupported", detail: issues[0] } : { ...base, state: "supported", detail: "Runs as explicit matchups" });
      return;
    }
    // Pool totals of a pool-v-pool stage (points per pool / per position across ties) are not computed
    // by the engine yet, so a later stage can't take qualifiers from one — block rather than rank wrongly.
    const src = sec.stages.find((x) => x.id === st.input?.fromStageId) ?? (i > 0 ? sec.stages[i - 1] : null);
    if (src?.kind === "cross_pool_league" && st.kind !== "cross_pool_league") {
      out.push({ ...base, state: "unsupported", detail: `${d.name} · ${st.name}: qualifying from ${src.name}'s pool-v-pool standings isn't supported by the engine yet (pool totals across ties aren't calculated).` });
      return;
    }
    out.push(ENGINE_KINDS.has(st.kind) ? { ...base, state: "supported", detail: "Supported" } : { ...base, state: "unsupported", detail: `${d.name} · ${st.name}: this stage type can't be generated yet.` });
  });
  return out;
}

export const engineBlockers = (def: TournamentDefinition) => engineVerdicts(def).filter((v) => v.state === "unsupported");
