/**
 * What SquashHub's tournament engine can actually generate and run — a HARD constraint on the
 * Smart Builder. Design, validation, Review and Create (specFromDefinition) all read this one list,
 * so the builder can never accept a stage that only fails later at Review/Create.
 *
 * Translation: a design that is exactly representable by supported stages is rewritten to them
 * (never just silenced). Today: a pool-v-pool singles league with position pairing, whose pools are
 * not used afterwards, is the same set of games as a round robin inside each "position group"
 * (every pool's #1 together, every #2 together…), seeded in bands.
 */
import type { Stage, TournamentDefinition } from "./definition";

/** Builder stage kinds the structured engine generates directly. */
export const ENGINE_KINDS = new Set(["round_robin", "knockout", "swiss", "placement"]);
/** Bookkeeping steps: no games of their own. */
const STEP_KINDS = new Set(["pair_from_positions", "split"]);

export interface EngineVerdict {
  stageId: string;
  divisionName: string;
  stageName: string;
  state: "supported" | "translated" | "unsupported";
  /** Plain explanation (translation used, or why it can't run). */
  detail: string;
}

/** Why a pool-v-pool stage can't be rewritten as position groups (null = it can). */
function positionGroupBlocker(st: Stage, index: number, stages: Stage[]): string | null {
  if (st.kind !== "cross_pool_league") return "not a pool-v-pool stage";
  if (st.discipline === "doubles") return "doubles pairs are formed from pool positions, which the engine can't do yet";
  if (index > 0) return "it doesn't open the division, so its pools can't be seeded directly";
  if (!st.groupSize || (st.groups ?? 0) < 2) return "pool count and pool size must be set";
  if (st.tieFormat?.pairing !== "position") return "only position-to-position pairing has a supported equivalent";
  const rubbers = st.tieFormat?.rubbers ?? [];
  const pos = rubbers.map((r) => (r.discipline === "singles" && r.positions?.length === 1 ? r.positions[0] : -1)).sort((a, b) => a - b);
  if (pos.length !== st.groupSize || pos.some((p, i) => p !== i + 1)) return "each pool position must play exactly one singles game per tie";
  const later = stages.slice(index + 1).find((x) => !STEP_KINDS.has(x.kind) || x.input?.fromStageId === st.id);
  const usesPools = stages.slice(index + 1).some((x) => x.kind === "pair_from_positions" || x.kind === "cross_pool_league" || (x as any).progression?.mode === "form_pairs" || x.sameSessionAs === st.id);
  if (usesPools) return "a later stage needs the pools themselves (pairs formed from pool positions / pool v pool again), which the engine can't track yet";
  if (later && st.standings?.method && st.standings.method !== "raw_total" && st.standings.method !== "result_points") return "its standings need pool totals";
  return null;
}

/** Rewrite a stage into its supported equivalent, or null when there isn't one. */
export function supportedEquivalent(st: Stage, index: number, stages: Stage[]): Stage | null {
  if (positionGroupBlocker(st, index, stages)) return null;
  return {
    ...structuredClone(st),
    kind: "round_robin",
    groups: st.groupSize!,
    groupSize: st.groups,
    tieFormat: undefined,
    notes: `${st.notes ? `${st.notes} ` : ""}Runs as ${st.groupSize} position groups of ${st.groups} (round robin, seeded in bands).`,
  } as Stage;
}

export function engineVerdicts(def: TournamentDefinition): EngineVerdict[] {
  const out: EngineVerdict[] = [];
  for (const d of def.divisions) for (const sec of d.sections) sec.stages.forEach((st, i) => {
    const base = { stageId: st.id, divisionName: d.name, stageName: st.name };
    if (STEP_KINDS.has(st.kind)) {
      out.push({ ...base, state: "unsupported", detail: `${d.name} · ${st.name}: this step type can't be generated by the tournament engine yet.` });
      return;
    }
    if (ENGINE_KINDS.has(st.kind)) { out.push({ ...base, state: "supported", detail: "Supported" }); return; }
    const eq = supportedEquivalent(st, i, sec.stages);
    if (eq) out.push({ ...base, state: "translated", detail: `${st.name}: runs as ${eq.groups} position groups of ${eq.groupSize} — the same games as the pool-v-pool rotation.` });
    else out.push({ ...base, state: "unsupported", detail: `${d.name} · ${st.name}: a pool-v-pool league can't be generated by the tournament engine — ${positionGroupBlocker(st, i, sec.stages)}.` });
  });
  return out;
}

export const engineBlockers = (def: TournamentDefinition) => engineVerdicts(def).filter((v) => v.state === "unsupported");

/** Definition as the engine will run it: translatable stages rewritten, everything else untouched. */
export function translateForEngine(def: TournamentDefinition): { def: TournamentDefinition; translatedDivisions: Set<string> } {
  const translatedDivisions = new Set<string>();
  const next = structuredClone(def);
  for (const d of next.divisions) for (const sec of d.sections) {
    sec.stages = sec.stages.map((st, i, all) => {
      if (st.kind !== "cross_pool_league") return st;
      const eq = supportedEquivalent(st, i, all);
      if (eq) translatedDivisions.add(d.id);
      return eq ?? st;
    });
  }
  return { def: next, translatedDivisions };
}
